import type { Metadata } from "next";
import "./globals.css";
import TopBar from "@/components/topBar/page";
import Footer from "@/components/footer/page";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/public/svg/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-primary bg-[url(https://apexnetwork.co/_nuxt/backgroundpattern.015223cf.svg)]">
        <TopBar/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
